# Generated by Django 4.1.4 on 2022-12-14 10:00

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo_path', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('date_delete', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('date_of_birth', models.DateTimeField()),
                ('photo_path', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo_path', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_delete', models.DateTimeField()),
                ('is_visible', models.BooleanField(default=True)),
                ('is_fixed', models.BooleanField()),
                ('discount_amount_absolute', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount_percent', models.IntegerField()),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DiscountService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.discount')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateTimeField()),
                ('phone', models.CharField(max_length=255)),
                ('photo_path', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('sport_category', models.IntegerField(choices=[(1, 'Master Of Sports Of International Class'), (2, 'Master Of Sports'), (3, 'Candidate For Master Of Sports'), (4, 'Without A Sports Category')])),
                ('date_delete', models.DateTimeField(null=True)),
                ('text_for_visit', models.TextField()),
                ('passwd', models.CharField(max_length=255)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('date_delete', models.DateTimeField(null=True)),
                ('is_group', models.BooleanField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sport_services', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Towel'), (2, 'Water Bottle'), (3, 'Sauna'), (4, 'Personal Locker'), (5, 'Disposable Slippers')]), null=True, size=None)),
                ('description', models.TextField()),
                ('group_status_changing', models.BooleanField(default=True, null=True)),
                ('max_clients', models.IntegerField()),
                ('advantages', models.ManyToManyField(to='fitness.advantage')),
                ('discounts', models.ManyToManyField(through='fitness.DiscountService', to='fitness.discount')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='fitness.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_path', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('date_delete', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.IntegerField()),
                ('description', models.TextField()),
                ('date_delete', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_individual', models.BooleanField(null=True)),
                ('date_cancel', models.DateTimeField()),
                ('comment', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.employee')),
            ],
        ),
        migrations.CreateModel(
            name='VisitService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.service')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.visit')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='photos',
            field=models.ManyToManyField(to='fitness.servicephoto'),
        ),
        migrations.AddField(
            model_name='service',
            name='subscriptions',
            field=models.ManyToManyField(to='fitness.subscription'),
        ),
        migrations.AddField(
            model_name='service',
            name='visits',
            field=models.ManyToManyField(through='fitness.VisitService', to='fitness.visit'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_delete', models.DateTimeField()),
                ('permissions', models.ManyToManyField(to='fitness.permission')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.service'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_phrase', models.CharField(max_length=255)),
                ('photo_path', models.ImageField(null=True, upload_to='photos/%Y/%m/%d/')),
                ('mark', models.IntegerField(choices=[(1, 'Bad'), (2, 'Not Satisfactory'), (3, 'Satisfactory'), (4, 'Good'), (5, 'Excellent')])),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_approve', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.employee')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.service')),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.service')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(to='fitness.role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(to='fitness.service'),
        ),
        migrations.AddField(
            model_name='discountservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.service'),
        ),
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.client')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.group')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.subscription')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(to='fitness.group'),
        ),
        migrations.AddField(
            model_name='client',
            name='subscriptions',
            field=models.ManyToManyField(through='fitness.ClientSubscription', to='fitness.subscription'),
        ),
    ]
