# Generated by Django 4.1.4 on 2023-01-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='clientsubscription',
            name='date_end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clientsubscription',
            name='date_start',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
