# Generated by Django 4.1.4 on 2022-12-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_client_mail_employee_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mail',
            field=models.CharField(max_length=255),
        ),
    ]
