# Generated by Django 4.1.4 on 2022-12-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_alter_client_mail_alter_employee_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='photo_path',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo_path',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_delete',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_amount_absolute',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_amount_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='photo_path',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo_path',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='photo_path',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='servicephoto',
            name='photo_path',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
