# Generated by Django 4.1.4 on 2022-12-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0004_alter_advantage_photo_path_alter_client_photo_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Клиенты', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateTimeField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.CharField(max_length=255, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo_path',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Фото'),
        ),
    ]
