# Generated by Django 4.1.4 on 2022-12-17 08:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_alter_client_options_alter_client_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='date_delete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='photo_path',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='fitness.group'),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo_path',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='client',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, null=True, through='fitness.ClientSubscription', to='fitness.subscription'),
        ),
        migrations.AlterField(
            model_name='clientsubscription',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness.group'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_delete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_amount_absolute',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_amount_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='photo_path',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_delete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo_path',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='fitness.service'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='text_for_visit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date_approve',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fitness.employee'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='photo_path',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fitness.service'),
        ),
        migrations.AlterField(
            model_name='role',
            name='date_delete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='advantages',
            field=models.ManyToManyField(blank=True, null=True, to='fitness.advantage'),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_delete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='discounts',
            field=models.ManyToManyField(blank=True, null=True, through='fitness.DiscountService', to='fitness.discount'),
        ),
        migrations.AlterField(
            model_name='service',
            name='group_status_changing',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_group',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='max_clients',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fitness.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='fitness.servicephoto'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='sport_services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(1, 'Towel'), (2, 'Water Bottle'), (3, 'Sauna'), (4, 'Personal Locker'), (5, 'Disposable Slippers')]), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='service',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, null=True, to='fitness.subscription'),
        ),
        migrations.AlterField(
            model_name='service',
            name='visits',
            field=models.ManyToManyField(blank=True, null=True, through='fitness.VisitService', to='fitness.visit'),
        ),
        migrations.AlterField(
            model_name='servicephoto',
            name='date_delete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='date_delete',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='date_cancel',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='is_individual',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
