# Generated by Django 4.1.4 on 2022-12-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_alter_advantage_date_delete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='fitness.role'),
        ),
    ]
