# Generated by Django 4.1.4 on 2022-12-18 01:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_alter_employee_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, null=True, size=None),
        ),
    ]
