# Generated by Django 4.1.4 on 2023-01-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_role_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetimetable',
            name='is_weekdays',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
