# Generated by Django 4.1.4 on 2023-01-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0013_servicetimetable_is_weekdays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetimetable',
            name='is_weekdays',
        ),
        migrations.AddField(
            model_name='service',
            name='end_work_holidays',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='end_work_weekends',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='start_work_holidays',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='start_work_weekends',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
