# Generated by Django 4.1.4 on 2023-01-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_remove_servicetimetable_is_weekdays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='passwd',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
